"""Closed P6.1 registries for Mock Registration and Institutional Demand V1."""

from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    MOCK_REG_UNKNOWN_COURSE = "MOCK_REG_UNKNOWN_COURSE"
    MOCK_REG_TARGET_NOT_PLAN_MEMBER = "MOCK_REG_TARGET_NOT_PLAN_MEMBER"
    MOCK_REG_TARGET_ALREADY_COMPLETED = "MOCK_REG_TARGET_ALREADY_COMPLETED"
    MOCK_REG_TARGET_IN_PROGRESS = "MOCK_REG_TARGET_IN_PROGRESS"
    MOCK_REG_TARGET_NOT_ELIGIBLE = "MOCK_REG_TARGET_NOT_ELIGIBLE"
    MOCK_REG_ELIGIBILITY_REVIEW_REQUIRED = "MOCK_REG_ELIGIBILITY_REVIEW_REQUIRED"
    MOCK_REG_ELECTIVE_GROUP_ALREADY_SATISFIED = "MOCK_REG_ELECTIVE_GROUP_ALREADY_SATISFIED"
    MOCK_REG_DUPLICATE_COURSE = "MOCK_REG_DUPLICATE_COURSE"
    MOCK_REG_EMPTY_COURSE_SET = "MOCK_REG_EMPTY_COURSE_SET"
    MOCK_REG_INVALID_PLAN_IDENTITY = "MOCK_REG_INVALID_PLAN_IDENTITY"
    MOCK_REG_INVALID_PLAN_VERSION = "MOCK_REG_INVALID_PLAN_VERSION"
    MOCK_REG_INVALID_TARGET_PERIOD = "MOCK_REG_INVALID_TARGET_PERIOD"
    MOCK_REG_INVALID_REVISION = "MOCK_REG_INVALID_REVISION"
    MOCK_REG_INVALID_LIFECYCLE = "MOCK_REG_INVALID_LIFECYCLE"
    MOCK_REG_COURSE_LIMIT_EXCEEDED = "MOCK_REG_COURSE_LIMIT_EXCEEDED"
    MOCK_REG_CREDIT_LIMIT_EXCEEDED = "MOCK_REG_CREDIT_LIMIT_EXCEEDED"
    MOCK_REG_REQUIRED_CONTEXT_MISSING = "MOCK_REG_REQUIRED_CONTEXT_MISSING"
    MOCK_REG_REVISION_SUPERSEDED = "MOCK_REG_REVISION_SUPERSEDED"
    MOCK_REG_REVISION_CONFLICT = "MOCK_REG_REVISION_CONFLICT"
    MOCK_REG_WITHDRAWN_INTENT = "MOCK_REG_WITHDRAWN_INTENT"
    MOCK_REG_EXPIRED_INTENT = "MOCK_REG_EXPIRED_INTENT"
    DEMAND_PRIVACY_SUPPRESSED = "DEMAND_PRIVACY_SUPPRESSED"
    DEMAND_NO_VALID_ACTIVE_INTENTS = "DEMAND_NO_VALID_ACTIVE_INTENTS"
    DEMAND_UNKNOWN_POPULATION_COVERAGE = "DEMAND_UNKNOWN_POPULATION_COVERAGE"
    DEMAND_PARTIAL_INTENT_COVERAGE = "DEMAND_PARTIAL_INTENT_COVERAGE"
    DEMAND_OFFERING_DATA_UNAVAILABLE = "DEMAND_OFFERING_DATA_UNAVAILABLE"
    DEMAND_CAPACITY_DATA_UNAVAILABLE = "DEMAND_CAPACITY_DATA_UNAVAILABLE"
    DEMAND_REVIEW_INTENTS_EXCLUDED = "DEMAND_REVIEW_INTENTS_EXCLUDED"
    DEMAND_SCOPE_MISMATCH = "DEMAND_SCOPE_MISMATCH"
    DEMAND_LIMIT_EXCEEDED = "DEMAND_LIMIT_EXCEEDED"


class DemandMetricId(str, Enum):
    VALID_ACTIVE_INTENT_OWNER_COUNT = "VALID_ACTIVE_INTENT_OWNER_COUNT"
    COURSE_INTENT_OWNER_COUNT = "COURSE_INTENT_OWNER_COUNT"
    COURSE_INTENT_SHARE_OF_VALID_INTENT_OWNERS = "COURSE_INTENT_SHARE_OF_VALID_INTENT_OWNERS"
    TOTAL_DECLARED_COURSE_SELECTION_COUNT = "TOTAL_DECLARED_COURSE_SELECTION_COUNT"
    TOTAL_DECLARED_CREDIT_LOAD = "TOTAL_DECLARED_CREDIT_LOAD"
    REQUIREMENT_GROUP_INTENT_OWNER_COUNT = "REQUIREMENT_GROUP_INTENT_OWNER_COUNT"
    PLAN_INTENT_OWNER_COUNT = "PLAN_INTENT_OWNER_COUNT"
    REVIEW_REQUIRED_INTENT_OWNER_COUNT = "REVIEW_REQUIRED_INTENT_OWNER_COUNT"
    DECLARED_DEMAND_MINUS_CAPACITY = "DECLARED_DEMAND_MINUS_CAPACITY"


class DataQualityFlag(str, Enum):
    COMPLETE_DECLARED_INTENT_INPUT_SET = "COMPLETE_DECLARED_INTENT_INPUT_SET"
    PARTIAL_INTENT_COVERAGE = "PARTIAL_INTENT_COVERAGE"
    UNKNOWN_POPULATION_COVERAGE = "UNKNOWN_POPULATION_COVERAGE"
    MISSING_OFFERING_DATA = "MISSING_OFFERING_DATA"
    MISSING_CAPACITY_DATA = "MISSING_CAPACITY_DATA"
    SUPPRESSED_FOR_PRIVACY = "SUPPRESSED_FOR_PRIVACY"
    REVIEW_REQUIRED_INTENTS_EXCLUDED = "REVIEW_REQUIRED_INTENTS_EXCLUDED"


METRIC_REGISTRY = tuple(DemandMetricId)
