"""Read-only student academic-state contract."""

from typing import Protocol
from uuid import UUID

from app.rules.models import AttemptOutcome
from app.student.models import StudentAcademicState, StudentCourseAttemptRecord


class StudentAcademicRepository(Protocol):
    async def load_student_academic_state(
        self, owner_user_id: UUID | str
    ) -> StudentAcademicState:
        """Load one owner's profile and every persisted attempt."""

    async def load_attempt_records(self, owner_user_id: UUID | str) -> tuple[StudentCourseAttemptRecord, ...]: ...
    async def create_profile(self, owner_user_id: UUID | str, study_plan_id: UUID | str, **facts) -> StudentAcademicState: ...
    async def update_profile(self, owner_user_id: UUID | str, **facts) -> StudentAcademicState: ...
    async def delete_profile(self, owner_user_id: UUID | str) -> None: ...
    async def create_attempt(self, owner_user_id: UUID | str, course_code: str, outcome: AttemptOutcome, **facts) -> StudentCourseAttemptRecord: ...
    async def update_attempt(self, owner_user_id: UUID | str, attempt_id: UUID | str, **facts) -> StudentCourseAttemptRecord: ...
    async def delete_attempt(self, owner_user_id: UUID | str, attempt_id: UUID | str) -> None: ...
