"""Closed, auditable registries for Institutional Intelligence V1."""

from __future__ import annotations

from enum import Enum


class InstitutionalSignalId(str, Enum):
    """The closed 13-signal registry for Institutional Intelligence V1."""

    INST_SIG_DECLARED_DEMAND_COUNT = "INST_SIG_DECLARED_DEMAND_COUNT"
    INST_SIG_DECLARED_DEMAND_SHARE = "INST_SIG_DECLARED_DEMAND_SHARE"
    INST_SIG_TOTAL_DECLARED_CREDIT_LOAD = "INST_SIG_TOTAL_DECLARED_CREDIT_LOAD"
    INST_SIG_REQUIREMENT_GROUP_DEMAND_COUNT = "INST_SIG_REQUIREMENT_GROUP_DEMAND_COUNT"
    INST_SIG_SUPPLIED_CAPACITY_COUNT = "INST_SIG_SUPPLIED_CAPACITY_COUNT"
    INST_SIG_DECLARED_CAPACITY_DEFICIT = "INST_SIG_DECLARED_CAPACITY_DEFICIT"
    INST_SIG_CAPACITY_PRESSURE_STATE = "INST_SIG_CAPACITY_PRESSURE_STATE"
    INST_SIG_DEMAND_TO_CAPACITY_RATIO = "INST_SIG_DEMAND_TO_CAPACITY_RATIO"
    INST_SIG_DIRECT_DOWNSTREAM_PREREQUISITE_COUNT = "INST_SIG_DIRECT_DOWNSTREAM_PREREQUISITE_COUNT"
    INST_SIG_TRANSITIVE_DOWNSTREAM_DEPENDENCY_COUNT = "INST_SIG_TRANSITIVE_DOWNSTREAM_DEPENDENCY_COUNT"
    INST_SIG_STRUCTURAL_MANDATORY_ROLE = "INST_SIG_STRUCTURAL_MANDATORY_ROLE"
    INST_SIG_STRUCTURAL_BOTTLENECK_STATUS = "INST_SIG_STRUCTURAL_BOTTLENECK_STATUS"
    INST_SIG_REVIEW_REQUIRED_INTENT_OWNER_COUNT = "INST_SIG_REVIEW_REQUIRED_INTENT_OWNER_COUNT"


class InstitutionalAlertId(str, Enum):
    """The closed 6-alert registry for Institutional Intelligence V1."""

    INST_ALERT_CAPACITY_DEFICIT_DETECTED = "INST_ALERT_CAPACITY_DEFICIT_DETECTED"
    INST_ALERT_ZERO_CAPACITY_WITH_DEMAND = "INST_ALERT_ZERO_CAPACITY_WITH_DEMAND"
    INST_ALERT_STRUCTURAL_BOTTLENECK_PRESSURE = "INST_ALERT_STRUCTURAL_BOTTLENECK_PRESSURE"
    INST_ALERT_REVIEW_REQUIRED_PRESENT = "INST_ALERT_REVIEW_REQUIRED_PRESENT"
    INST_ALERT_CAPACITY_DATA_MISSING = "INST_ALERT_CAPACITY_DATA_MISSING"
    INST_ALERT_OFFERING_DATA_MISSING = "INST_ALERT_OFFERING_DATA_MISSING"


class SignalStatus(str, Enum):
    """Exact 5-status finite vocabulary for institutional signals."""

    AVAILABLE = "AVAILABLE"
    SUPPRESSED = "SUPPRESSED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CapacityPressureState(str, Enum):
    """Deterministic 4-valued state for capacity pressure comparison."""

    NO_CAPACITY_DATA = "NO_CAPACITY_DATA"
    WITHIN_SUPPLIED_CAPACITY = "WITHIN_SUPPLIED_CAPACITY"
    DECLARED_DEMAND_EXCEEDS_SUPPLIED_CAPACITY = "DECLARED_DEMAND_EXCEEDS_SUPPLIED_CAPACITY"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class StructuralGatewayStatus(str, Enum):
    """Deterministic structural gateway classification."""

    STRUCTURAL_GATEWAY = "STRUCTURAL_GATEWAY"
    NON_GATEWAY = "NON_GATEWAY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class StructuralMandatoryRole(str, Enum):
    """Individually mandatory role of a course under the study plan."""

    MANDATORY_REQUIRED = "MANDATORY_REQUIRED"
    CHOICE_ELECTIVE = "CHOICE_ELECTIVE"


class PlannedOfferingStatus(str, Enum):
    """Authoritative planned course offering status."""

    OFFERED = "OFFERED"
    NOT_OFFERED = "NOT_OFFERED"


class AlertSideEffect(str, Enum):
    """Alerts represent conditions only and produce zero side-effects."""

    NONE = "NONE"


class InstitutionalFactAuthority(str, Enum):
    """Authoritative provenance classification for external institutional facts."""

    VERIFIED_INSTITUTIONAL_FACT = "VERIFIED_INSTITUTIONAL_FACT"
    SYNTHETIC_SANDBOX_FACT = "SYNTHETIC_SANDBOX_FACT"


class InstitutionalScopeType(str, Enum):
    """Academic scopes for institutional queries and signals."""

    UNIVERSITY_WIDE = "UNIVERSITY_WIDE"
    PLAN_SCOPED = "PLAN_SCOPED"
    COURSE_SCOPE = "COURSE_SCOPE"
    REQUIREMENT_GROUP_SCOPE = "REQUIREMENT_GROUP_SCOPE"
    PERIOD_SCOPE = "PERIOD_SCOPE"


INSTITUTIONAL_SIGNAL_REGISTRY = tuple(InstitutionalSignalId)
INSTITUTIONAL_ALERT_REGISTRY = tuple(InstitutionalAlertId)
