from __future__ import annotations
from enum import Enum

class DecisionType(str, Enum):
    MOCK_REGISTRATION_SUBMIT='MOCK_REGISTRATION_SUBMIT'
    MOCK_REGISTRATION_WITHDRAW='MOCK_REGISTRATION_WITHDRAW'
    MOCK_REGISTRATION_REVALIDATE='MOCK_REGISTRATION_REVALIDATE'
    ADVISOR_FORMAL_GUIDANCE='ADVISOR_FORMAL_GUIDANCE'
    INSTITUTIONAL_PERIOD_DEMAND_SNAPSHOT='INSTITUTIONAL_PERIOD_DEMAND_SNAPSHOT'
    INSTITUTIONAL_BOTTLENECK_SNAPSHOT='INSTITUTIONAL_BOTTLENECK_SNAPSHOT'
    INSTITUTIONAL_ALERT_TRIGGERED='INSTITUTIONAL_ALERT_TRIGGERED'
    CHANGE_IMPACT_EVALUATION='CHANGE_IMPACT_EVALUATION'
    FORMAL_POLICY_CONSULTATION='FORMAL_POLICY_CONSULTATION'
    CHECK_ELIGIBILITY='CHECK_ELIGIBILITY'
    GET_PROGRESS='GET_PROGRESS'
    GET_RECOMMENDATIONS='GET_RECOMMENDATIONS'
    GET_SEMESTER_PLANS='GET_SEMESTER_PLANS'
    GET_DEGREE_PATHS='GET_DEGREE_PATHS'
    GET_STUDENT_INTELLIGENCE='GET_STUDENT_INTELLIGENCE'
    CHECK_DELAY_CONSEQUENCE='CHECK_DELAY_CONSEQUENCE'
    RUN_WHAT_IF='RUN_WHAT_IF'
    GET_CURRENT_MOCK_REGISTRATION='GET_CURRENT_MOCK_REGISTRATION'
    EXPLAIN_RECOMMENDATION_DECISION='EXPLAIN_RECOMMENDATION_DECISION'
    INSTITUTIONAL_AD_HOC_QUERY='INSTITUTIONAL_AD_HOC_QUERY'
    POLICY_AD_HOC_CHAT='POLICY_AD_HOC_CHAT'

class MaterialityClass(str, Enum):
    LEDGER_REQUIRED='LEDGER_REQUIRED'; LEDGER_OPTIONAL='LEDGER_OPTIONAL'; DOMAIN_TRACE_ONLY='DOMAIN_TRACE_ONLY'; NOT_LEDGERED='NOT_LEDGERED'
class ActorClass(str, Enum):
    STUDENT='STUDENT'; ACADEMIC_ADVISOR='ACADEMIC_ADVISOR'; INSTITUTIONAL_ANALYST='INSTITUTIONAL_ANALYST'; AUTHORIZED_AUDITOR='AUTHORIZED_AUDITOR'; SYSTEM_SCHEDULER='SYSTEM_SCHEDULER'; SYSTEM_ENGINE='SYSTEM_ENGINE'
class SubjectScopeType(str, Enum):
    STUDENT_INDIVIDUAL='STUDENT_INDIVIDUAL'; INSTITUTIONAL_PERIOD='INSTITUTIONAL_PERIOD'; CURRICULAR_PROGRAM='CURRICULAR_PROGRAM'; POLICY_DOCUMENT='POLICY_DOCUMENT'
class DecisionStatus(str, Enum):
    EXECUTED='EXECUTED'; VALIDATED='VALIDATED'; REVALIDATED_VALID='REVALIDATED_VALID'; REVALIDATED_INVALID='REVALIDATED_INVALID'; ABSTAINED='ABSTAINED'; FLAGGED_REVIEW='FLAGGED_REVIEW'; SUPERSEDED='SUPERSEDED'
class ProvenanceClass(str, Enum):
    AUTHORITATIVE_TRANSACTION='AUTHORITATIVE_TRANSACTION'; VERIFIED_REVALIDATION='VERIFIED_REVALIDATION'; PERIOD_SNAPSHOT='PERIOD_SNAPSHOT'; GOVERNED_ASSESSMENT='GOVERNED_ASSESSMENT'
class ReplayMode(str, Enum):
    EXACT_REPLAY='EXACT_REPLAY'; CURRENT_RECOMPUTATION='CURRENT_RECOMPUTATION'; NOT_REPLAYABLE='NOT_REPLAYABLE'
class ReplayStatus(str, Enum):
    REPLAYABLE_EXACT='REPLAYABLE_EXACT'; REPLAYABLE_CURRENT_ONLY='REPLAYABLE_CURRENT_ONLY'; NOT_REPLAYABLE='NOT_REPLAYABLE'
class RedactionProfile(str, Enum):
    STUDENT_SAFE='STUDENT_SAFE'; ADVISOR_SAFE='ADVISOR_SAFE'; AGGREGATE_ANALYST='AGGREGATE_ANALYST'; FULL_AUDIT='FULL_AUDIT'; PUBLIC_REDACTED='PUBLIC_REDACTED'
class IntegrityStatus(str, Enum):
    VERIFIED='VERIFIED'; TAMPER_DETECTED='TAMPER_DETECTED'; MALFORMED_HASH='MALFORMED_HASH'; MISSING_HASH='MISSING_HASH'

DECISION_MATERIALITY_REGISTRY={
    DecisionType.MOCK_REGISTRATION_SUBMIT:MaterialityClass.LEDGER_REQUIRED,
    DecisionType.MOCK_REGISTRATION_WITHDRAW:MaterialityClass.LEDGER_REQUIRED,
    DecisionType.MOCK_REGISTRATION_REVALIDATE:MaterialityClass.LEDGER_REQUIRED,
    DecisionType.ADVISOR_FORMAL_GUIDANCE:MaterialityClass.LEDGER_REQUIRED,
    DecisionType.INSTITUTIONAL_PERIOD_DEMAND_SNAPSHOT:MaterialityClass.LEDGER_REQUIRED,
    DecisionType.INSTITUTIONAL_BOTTLENECK_SNAPSHOT:MaterialityClass.LEDGER_REQUIRED,
    DecisionType.INSTITUTIONAL_ALERT_TRIGGERED:MaterialityClass.LEDGER_REQUIRED,
    DecisionType.CHANGE_IMPACT_EVALUATION:MaterialityClass.LEDGER_REQUIRED,
    DecisionType.FORMAL_POLICY_CONSULTATION:MaterialityClass.LEDGER_OPTIONAL,
    DecisionType.CHECK_ELIGIBILITY:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.GET_PROGRESS:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.GET_RECOMMENDATIONS:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.GET_SEMESTER_PLANS:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.GET_DEGREE_PATHS:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.GET_STUDENT_INTELLIGENCE:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.CHECK_DELAY_CONSEQUENCE:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.RUN_WHAT_IF:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.GET_CURRENT_MOCK_REGISTRATION:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.EXPLAIN_RECOMMENDATION_DECISION:MaterialityClass.DOMAIN_TRACE_ONLY,
    DecisionType.INSTITUTIONAL_AD_HOC_QUERY:MaterialityClass.NOT_LEDGERED,
    DecisionType.POLICY_AD_HOC_CHAT:MaterialityClass.NOT_LEDGERED,
}

def materiality_for(decision_type:DecisionType)->MaterialityClass:
    try: return DECISION_MATERIALITY_REGISTRY[decision_type]
    except KeyError as exc: raise ValueError(f'Unsupported decision type: {decision_type!r}') from exc
