"""Phase P7.5 Advisor Copilot Tool Registry & Authority Class Contracts.

Locks the closed, finite set of 11 read-only tools defined by Phase P7.1.
All tools have side_effects = "NONE".
"""

from __future__ import annotations

from enum import Enum


class AdvisorToolId(str, Enum):
    """The closed, authoritative 11-tool registry for Advisor Copilot."""

    ADVISOR_TOOL_GET_ACADEMIC_SNAPSHOT = "ADVISOR_TOOL_GET_ACADEMIC_SNAPSHOT"
    ADVISOR_TOOL_GET_PROGRESS = "ADVISOR_TOOL_GET_PROGRESS"
    ADVISOR_TOOL_CHECK_ELIGIBILITY = "ADVISOR_TOOL_CHECK_ELIGIBILITY"
    ADVISOR_TOOL_GET_RECOMMENDATIONS = "ADVISOR_TOOL_GET_RECOMMENDATIONS"
    ADVISOR_TOOL_GET_SEMESTER_PLANS = "ADVISOR_TOOL_GET_SEMESTER_PLANS"
    ADVISOR_TOOL_GET_DEGREE_PATHS = "ADVISOR_TOOL_GET_DEGREE_PATHS"
    ADVISOR_TOOL_GET_STUDENT_INTELLIGENCE = "ADVISOR_TOOL_GET_STUDENT_INTELLIGENCE"
    ADVISOR_TOOL_CHECK_DELAY_CONSEQUENCE = "ADVISOR_TOOL_CHECK_DELAY_CONSEQUENCE"
    ADVISOR_TOOL_RUN_WHAT_IF = "ADVISOR_TOOL_RUN_WHAT_IF"
    ADVISOR_TOOL_GET_CURRENT_MOCK_REGISTRATION = "ADVISOR_TOOL_GET_CURRENT_MOCK_REGISTRATION"
    ADVISOR_TOOL_EXPLAIN_RECOMMENDATION_DECISION = "ADVISOR_TOOL_EXPLAIN_RECOMMENDATION_DECISION"


class ToolAuthorityClass(str, Enum):
    """Authority classifications contracted by Phase P7.1."""

    DETERMINISTIC_EVIDENCE = "DETERMINISTIC_EVIDENCE"
    EPHEMERAL_SIMULATION = "EPHEMERAL_SIMULATION"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    GENERAL_INFORMATION = "GENERAL_INFORMATION"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"


# Machine-locked side-effects: every tool is strictly read-only / NONE.
TOOL_SIDE_EFFECTS: dict[AdvisorToolId, str] = {
    AdvisorToolId.ADVISOR_TOOL_GET_ACADEMIC_SNAPSHOT: "NONE",
    AdvisorToolId.ADVISOR_TOOL_GET_PROGRESS: "NONE",
    AdvisorToolId.ADVISOR_TOOL_CHECK_ELIGIBILITY: "NONE",
    AdvisorToolId.ADVISOR_TOOL_GET_RECOMMENDATIONS: "NONE",
    AdvisorToolId.ADVISOR_TOOL_GET_SEMESTER_PLANS: "NONE",
    AdvisorToolId.ADVISOR_TOOL_GET_DEGREE_PATHS: "NONE",
    AdvisorToolId.ADVISOR_TOOL_GET_STUDENT_INTELLIGENCE: "NONE",
    AdvisorToolId.ADVISOR_TOOL_CHECK_DELAY_CONSEQUENCE: "NONE",
    AdvisorToolId.ADVISOR_TOOL_RUN_WHAT_IF: "NONE",
    AdvisorToolId.ADVISOR_TOOL_GET_CURRENT_MOCK_REGISTRATION: "NONE",
    AdvisorToolId.ADVISOR_TOOL_EXPLAIN_RECOMMENDATION_DECISION: "NONE",
}

# Authority classification mapping
TOOL_AUTHORITY_CLASSES: dict[AdvisorToolId, ToolAuthorityClass] = {
    AdvisorToolId.ADVISOR_TOOL_GET_ACADEMIC_SNAPSHOT: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_GET_PROGRESS: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_CHECK_ELIGIBILITY: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_GET_RECOMMENDATIONS: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_GET_SEMESTER_PLANS: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_GET_DEGREE_PATHS: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_GET_STUDENT_INTELLIGENCE: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_CHECK_DELAY_CONSEQUENCE: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_RUN_WHAT_IF: ToolAuthorityClass.EPHEMERAL_SIMULATION,
    AdvisorToolId.ADVISOR_TOOL_GET_CURRENT_MOCK_REGISTRATION: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
    AdvisorToolId.ADVISOR_TOOL_EXPLAIN_RECOMMENDATION_DECISION: ToolAuthorityClass.DETERMINISTIC_EVIDENCE,
}

# Target period applicability: only Mock Registration requires a planning period.
TOOL_REQUIRES_TARGET_PERIOD: dict[AdvisorToolId, bool] = {
    AdvisorToolId.ADVISOR_TOOL_GET_ACADEMIC_SNAPSHOT: False,
    AdvisorToolId.ADVISOR_TOOL_GET_PROGRESS: False,
    AdvisorToolId.ADVISOR_TOOL_CHECK_ELIGIBILITY: False,
    AdvisorToolId.ADVISOR_TOOL_GET_RECOMMENDATIONS: False,
    AdvisorToolId.ADVISOR_TOOL_GET_SEMESTER_PLANS: False,
    AdvisorToolId.ADVISOR_TOOL_GET_DEGREE_PATHS: False,
    AdvisorToolId.ADVISOR_TOOL_GET_STUDENT_INTELLIGENCE: False,
    AdvisorToolId.ADVISOR_TOOL_CHECK_DELAY_CONSEQUENCE: False,
    AdvisorToolId.ADVISOR_TOOL_RUN_WHAT_IF: False,
    AdvisorToolId.ADVISOR_TOOL_GET_CURRENT_MOCK_REGISTRATION: True,
    AdvisorToolId.ADVISOR_TOOL_EXPLAIN_RECOMMENDATION_DECISION: False,
}
